name: Build and deploy mdbook

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Get mdbook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'
      - name: Build the books and deploy
        run: |
          for f in exercises/*; do
            cd $f
            mdbook build
            mkdir -p ../../docs/$f
            cp -r book/* ../../docs/$f
            cd ../..
          done
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Build and deploy mdbook"
